export const columns = [
   {name: 'NOME', uid: 'name'},
   {name: 'MODELO', uid: 'role'},
   {name: 'STATUS', uid: 'status'},
   {name: 'AÇÕES', uid: 'actions'},
];

export const users = [
   {
      id: 1,
      name: 'A01',
      role: 'LG',
      team: 'Dual Inverter',
      status: 'ligado',
      age: '29',
      avatar: 'success',
      email: '2 Aparelhos',
   },
   {
      id: 2,
      name: 'A02',
      role: 'Samsung',
      team: 'Split',
      status: 'desligado',
      age: '25',
      avatar: 'warning',
      email: '1 Aparelho',
   },
   {
      id: 3,
      name: 'A03',
      role: 'Elgin',
      team: 'Split',
      status: 'ligado',
      age: '22',
      avatar: 'success',
      email: '2 Aparelhos',
   },
   {
      id: 4,
      name: 'A04',
      role: 'Consul',
      team: 'Inverter',
      status: 'reparo',
      age: '28',
      avatar: 'error',
      email: 'Aparelhos retirados para manutenção',
   },
   {
      id: 5,
      name: 'A05',
      role: 'Komeco',
      team: 'Split',
      status: 'ligado',
      age: '24',
      avatar: 'success',
      email: '3 Aparelhos',
   },
   {
      id: 6,
      name: 'A06',
      role: 'LG',
      team: 'Dual Inverter',
      status: 'ligado',
      age: '29',
      avatar: 'success',
      email: '2 Aparelhos',
   },
   {
      id: 7,
      name: 'A07',
      role: 'Komeco',
      team: 'Split',
      status: 'ligado',
      age: '24',
      avatar: 'success',
      email: '3 Aparelhos',
   },
   {
      id: 8,
      name: 'A08',
      role: 'Elgin',
      team: 'Split',
      status: 'ligado',
      age: '22',
      avatar: 'success',
      email: '2 Aparelhos',
   },
   {
      id: 9,
      name: 'A09',
      role: 'Samsung',
      team: 'Split',
      status: 'desligado',
      age: '25',
      avatar: 'warning',
      email: '1 Aparelho',
   },

   {
      id: 10,
      name: 'A10',
      role: 'Consul',
      team: 'Inverter',
      status: 'reparo',
      age: '28',
      avatar: 'error',
      email: 'Aparelhos retirados para manutenção',
   },
   {
      id: 11,
      name: 'A11',
      role: 'LG',
      team: 'Dual Inverter',
      status: 'ligado',
      age: '29',
      avatar: 'success',
      email: '2 Aparelhos',
   },
   {
      id: 12,
      name: 'A12',
      role: 'Komeco',
      team: 'Split',
      status: 'ligado',
      age: '24',
      avatar: 'success',
      email: '3 Aparelhos',
   },
   {
      id: 13,
      name: 'A13',
      role: 'Elgin',
      team: 'Split',
      status: 'ligado',
      age: '22',
      avatar: 'success',
      email: '2 Aparelhos',
   },
   {
      id: 14,
      name: 'A14',
      role: 'Samsung',
      team: 'Split',
      status: 'desligado',
      age: '25',
      avatar: 'warning',
      email: '1 Aparelho',
   },
   {
      id: 15,
      name: 'A15',
      role: 'LG',
      team: 'Dual Inverter',
      status: 'ligado',
      age: '29',
      avatar: 'success',
      email: '2 Aparelhos',
   },
   {
      id: 16,
      name: 'A16',
      role: 'Komeco',
      team: 'Split',
      status: 'ligado',
      age: '24',
      avatar: 'success',
      email: '3 Aparelhos',
   },
];
